### PR TITLE
Adds condition to only create a ws client when executing a subscription operation

### LINKED ISSUE #360: Cannot execute any query or mutation
## Actual Behavior

Cannot execute query or mutation. Not showing any errors.

Running the extension locally and adding a console.error for the actual error I got the message below:
`Invalid WebSocket implementation provided  at createClient`

## Expected Behavior

Being able to execute a query or mutation

## Steps to Reproduce the Problem Or Description

Try execute any query or mutation

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.26
  - VSCode Version: 1.62.3
  - OS Name: OSX
  - OS Version: Monterey
  - graphql config filename and format example: .graphqlrc.yml

## Logs Of TS Server || GraphQL Language Service

There are no logs since the query is not actually executing

### PR DESCRIPTION
**Pull request by edusig**
Fix #360

### CODE REVIEW

**Comment by acao** [comment]
thank you!

**Comment by acao** [comment]
Otherwise, things seem ok overall with the client upgrade/refactor?

**Comment by edusig** [comment]
I started using this extension yesterday so I can't say much about the upgrade/refactor.
I haven't tested a subscription operation yet, but this PR should only fix for query and mutation.

The only problem I still have is that, even though I configured my workspace to change the base path for the GraphQL config file, it still wouldn't  find it. This sucks because I work a lot with monorepos and use graphql-code-generator, so right now I have to maintain 2 separate GraphQL config files.

**Comment by acao** [comment]
Huh, that does suck. We have some open bugs for adding vscode multi-root workspaces support that we need to resolve, as we never adopted that feature when vscode introduced it a long time ago.

 Currently the language server expects one graphql config file as graphql-config expects, so we need to update the language service cacheing strategy to support multiple graphql config instances for each config file.

**Pull request merged**
